services:
  db:
    image: postgres:17
    container_name: whatsappgiodb
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: gio
      POSTGRES_PASSWORD: gio
      POSTGRES_DB: whatsappgiodb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  proxy:
    image: nginx:alpine
    container_name: dev-proxy
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
    restart: unless-stopped
