package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
)

// Example is the resolver for the example field.
func (r *mutationResolver) Example(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Example - example"))
}

// Example is the resolver for the example field.
func (r *queryResolver) Example(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Example - example"))
}

// Example is the resolver for the example field.
func (r *subscriptionResolver) Example(ctx context.Context) (<-chan *string, error) {
	panic(fmt.Errorf("not implemented: Example - example"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
