package repository

var (
	MESSAGE_TYPE_TEXT  = "TEXT"
	MESSAGE_TYPE_IMAGE = "IMAGE"
	MESSAGE_TYPE_FILE  = "FILE"

	MESSAGE_STATUS_SENT      = "SENT"
	MESSAGE_STATUS_DELIVERED = "DELIVERED"
	MESSAGE_STATUS_READ      = "READ"
	MESSAGE_STATUS_FAILED    = "FAILED"
)
